/* Generated By:JJTree&JavaCC: Do not edit this line. OrbConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
#ifndef ORBCONSTANTS_H
#define ORBCONSTANTS_H
#include "JavaCC.h"

  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
const  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
const  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
const  int T_ALIAS = 12;
  /** RegularExpression Id. */
const  int T_AND = 13;
  /** RegularExpression Id. */
const  int T_BREAK = 14;
  /** RegularExpression Id. */
const  int T_CASE = 15;
  /** RegularExpression Id. */
const  int T_CONST = 16;
  /** RegularExpression Id. */
const  int T_CONTINUE = 17;
  /** RegularExpression Id. */
const  int T_DEFAULT = 18;
  /** RegularExpression Id. */
const  int T_DO = 19;
  /** RegularExpression Id. */
const  int T_ELIF = 20;
  /** RegularExpression Id. */
const  int T_ELSE = 21;
  /** RegularExpression Id. */
const  int T_END = 22;
  /** RegularExpression Id. */
const  int T_FALSE = 23;
  /** RegularExpression Id. */
const  int T_FOR = 24;
  /** RegularExpression Id. */
const  int T_FUNCTION = 25;
  /** RegularExpression Id. */
const  int T_IF = 26;
  /** RegularExpression Id. */
const  int T_IS = 27;
  /** RegularExpression Id. */
const  int T_LOCAL = 28;
  /** RegularExpression Id. */
const  int T_NIL = 29;
  /** RegularExpression Id. */
const  int T_OR = 30;
  /** RegularExpression Id. */
const  int T_PACKAGE = 31;
  /** RegularExpression Id. */
const  int T_PROPERTY = 32;
  /** RegularExpression Id. */
const  int T_PUBLIC = 33;
  /** RegularExpression Id. */
const  int T_READONLY = 34;
  /** RegularExpression Id. */
const  int T_READWRITE = 35;
  /** RegularExpression Id. */
const  int T_RETURN = 36;
  /** RegularExpression Id. */
const  int T_THEN = 37;
  /** RegularExpression Id. */
const  int T_THIS = 38;
  /** RegularExpression Id. */
const  int T_TRUE = 39;
  /** RegularExpression Id. */
const  int T_TYPEOF = 40;
  /** RegularExpression Id. */
const  int T_USING = 41;
  /** RegularExpression Id. */
const  int T_WHEN = 42;
  /** RegularExpression Id. */
const  int T_WHILE = 43;
  /** RegularExpression Id. */
const  int T_WRITEONLY = 44;
  /** RegularExpression Id. */
const  int INTEGER_LITERAL = 45;
  /** RegularExpression Id. */
const  int DECIMAL_LITERAL = 46;
  /** RegularExpression Id. */
const  int HEX_LITERAL = 47;
  /** RegularExpression Id. */
const  int FLOATING_POINT_LITERAL = 48;
  /** RegularExpression Id. */
const  int EXPONENT = 49;
  /** RegularExpression Id. */
const  int CHARACTER_LITERAL = 50;
  /** RegularExpression Id. */
const  int STRING_LITERAL = 51;
  /** RegularExpression Id. */
const  int IDENTIFIER = 52;
  /** RegularExpression Id. */
const  int LETTER = 53;
  /** RegularExpression Id. */
const  int PART_LETTER = 54;
  /** RegularExpression Id. */
const  int GREECE_LETTER = 55;

  /** Lexical state. */
const  int DEFAULT = 0;
  /** Lexical state. */
const  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
const  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
const  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  static const JJChar tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenImage_arr_1[] = 
{0x22, 0x20, 0x22, 0};
  static const JJChar tokenImage_arr_2[] = 
{0x22, 0x9, 0x22, 0};
  static const JJChar tokenImage_arr_3[] = 
{0x22, 0xa, 0x22, 0};
  static const JJChar tokenImage_arr_4[] = 
{0x22, 0xd, 0x22, 0};
  static const JJChar tokenImage_arr_5[] = 
{0x22, 0x2f, 0x2f, 0x22, 0};
  static const JJChar tokenImage_arr_6[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x36, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_7[] = 
{0x22, 0x2f, 0x2a, 0x22, 0};
  static const JJChar tokenImage_arr_8[] = 
{0x22, 0x3c, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x5f, 0x4c, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_9[] = 
{0x22, 0x2a, 0x2f, 0x22, 0};
  static const JJChar tokenImage_arr_10[] = 
{0x22, 0x2a, 0x2f, 0x22, 0};
  static const JJChar tokenImage_arr_11[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x31, 0x31, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_12[] = 
{0x22, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0};
  static const JJChar tokenImage_arr_13[] = 
{0x22, 0x61, 0x6e, 0x64, 0x22, 0};
  static const JJChar tokenImage_arr_14[] = 
{0x22, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x22, 0};
  static const JJChar tokenImage_arr_15[] = 
{0x22, 0x63, 0x61, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_16[] = 
{0x22, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x22, 0};
  static const JJChar tokenImage_arr_17[] = 
{0x22, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_18[] = 
{0x22, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0};
  static const JJChar tokenImage_arr_19[] = 
{0x22, 0x64, 0x6f, 0x22, 0};
  static const JJChar tokenImage_arr_20[] = 
{0x22, 0x65, 0x6c, 0x69, 0x66, 0x22, 0};
  static const JJChar tokenImage_arr_21[] = 
{0x22, 0x65, 0x6c, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_22[] = 
{0x22, 0x65, 0x6e, 0x64, 0x22, 0};
  static const JJChar tokenImage_arr_23[] = 
{0x22, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_24[] = 
{0x22, 0x66, 0x6f, 0x72, 0x22, 0};
  static const JJChar tokenImage_arr_25[] = 
{0x22, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0};
  static const JJChar tokenImage_arr_26[] = 
{0x22, 0x69, 0x66, 0x22, 0};
  static const JJChar tokenImage_arr_27[] = 
{0x22, 0x69, 0x73, 0x22, 0};
  static const JJChar tokenImage_arr_28[] = 
{0x22, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x22, 0};
  static const JJChar tokenImage_arr_29[] = 
{0x22, 0x6e, 0x69, 0x6c, 0x22, 0};
  static const JJChar tokenImage_arr_30[] = 
{0x22, 0x6f, 0x72, 0x22, 0};
  static const JJChar tokenImage_arr_31[] = 
{0x22, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_32[] = 
{0x22, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x22, 0};
  static const JJChar tokenImage_arr_33[] = 
{0x22, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x22, 0};
  static const JJChar tokenImage_arr_34[] = 
{0x22, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x22, 0};
  static const JJChar tokenImage_arr_35[] = 
{0x22, 0x72, 0x65, 0x61, 0x64, 0x77, 0x72, 0x69, 0x74, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_36[] = 
{0x22, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0};
  static const JJChar tokenImage_arr_37[] = 
{0x22, 0x74, 0x68, 0x65, 0x6e, 0x22, 0};
  static const JJChar tokenImage_arr_38[] = 
{0x22, 0x74, 0x68, 0x69, 0x73, 0x22, 0};
  static const JJChar tokenImage_arr_39[] = 
{0x22, 0x74, 0x72, 0x75, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_40[] = 
{0x22, 0x74, 0x79, 0x70, 0x65, 0x6f, 0x66, 0x22, 0};
  static const JJChar tokenImage_arr_41[] = 
{0x22, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x22, 0};
  static const JJChar tokenImage_arr_42[] = 
{0x22, 0x77, 0x68, 0x65, 0x6e, 0x22, 0};
  static const JJChar tokenImage_arr_43[] = 
{0x22, 0x77, 0x68, 0x69, 0x6c, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_44[] = 
{0x22, 0x77, 0x72, 0x69, 0x74, 0x65, 0x6f, 0x6e, 0x6c, 0x79, 0x22, 0};
  static const JJChar tokenImage_arr_45[] = 
{0x22, 0x3c, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_46[] = 
{0x22, 0x3c, 0x44, 0x45, 0x43, 0x49, 0x4d, 0x41, 0x4c, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_47[] = 
{0x22, 0x3c, 0x48, 0x45, 0x58, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_48[] = 
{0x22, 0x3c, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_49[] = 
{0x22, 0x3c, 0x45, 0x58, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_50[] = 
{0x22, 0x3c, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_51[] = 
{0x22, 0x3c, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_52[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_53[] = 
{0x22, 0x3c, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_54[] = 
{0x22, 0x3c, 0x50, 0x41, 0x52, 0x54, 0x5f, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_55[] = 
{0x22, 0x3c, 0x47, 0x52, 0x45, 0x45, 0x43, 0x45, 0x5f, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_56[] = 
{0x22, 0x3b, 0x22, 0};
  static const JJChar tokenImage_arr_57[] = 
{0x22, 0x2e, 0x22, 0};
  static const JJChar tokenImage_arr_58[] = 
{0x22, 0x2a, 0x22, 0};
  static const JJChar tokenImage_arr_59[] = 
{0x22, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_60[] = 
{0x22, 0x28, 0x22, 0};
  static const JJChar tokenImage_arr_61[] = 
{0x22, 0x29, 0x22, 0};
  static const JJChar tokenImage_arr_62[] = 
{0x22, 0x2c, 0x22, 0};
  static const JJChar tokenImage_arr_63[] = 
{0x22, 0x2e, 0x2e, 0x2e, 0x22, 0};
  static const JJChar tokenImage_arr_64[] = 
{0x22, 0x5b, 0x22, 0};
  static const JJChar tokenImage_arr_65[] = 
{0x22, 0x3a, 0x22, 0};
  static const JJChar tokenImage_arr_66[] = 
{0x22, 0x5d, 0x22, 0};
  static const JJChar tokenImage_arr_67[] = 
{0x22, 0x2b, 0x2b, 0x22, 0};
  static const JJChar tokenImage_arr_68[] = 
{0x22, 0x2d, 0x2d, 0x22, 0};
  static const JJChar tokenImage_arr_69[] = 
{0x22, 0x7b, 0x22, 0};
  static const JJChar tokenImage_arr_70[] = 
{0x22, 0x7d, 0x22, 0};
  static const JJChar tokenImage_arr_71[] = 
{0x22, 0x2a, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_72[] = 
{0x22, 0x2f, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_73[] = 
{0x22, 0x25, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_74[] = 
{0x22, 0x2b, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_75[] = 
{0x22, 0x2d, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_76[] = 
{0x22, 0x26, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_77[] = 
{0x22, 0x5e, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_78[] = 
{0x22, 0x7c, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_79[] = 
{0x22, 0x3f, 0x22, 0};
  static const JJChar tokenImage_arr_80[] = 
{0x22, 0x7c, 0x7c, 0x22, 0};
  static const JJChar tokenImage_arr_81[] = 
{0x22, 0x26, 0x26, 0x22, 0};
  static const JJChar tokenImage_arr_82[] = 
{0x22, 0x7c, 0x22, 0};
  static const JJChar tokenImage_arr_83[] = 
{0x22, 0x5e, 0x22, 0};
  static const JJChar tokenImage_arr_84[] = 
{0x22, 0x26, 0x22, 0};
  static const JJChar tokenImage_arr_85[] = 
{0x22, 0x3d, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_86[] = 
{0x22, 0x7e, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_87[] = 
{0x22, 0x3c, 0x22, 0};
  static const JJChar tokenImage_arr_88[] = 
{0x22, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_89[] = 
{0x22, 0x3c, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_90[] = 
{0x22, 0x3e, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_91[] = 
{0x22, 0x3c, 0x3c, 0x22, 0};
  static const JJChar tokenImage_arr_92[] = 
{0x22, 0x3e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_93[] = 
{0x22, 0x3e, 0x3e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_94[] = 
{0x22, 0x2b, 0x22, 0};
  static const JJChar tokenImage_arr_95[] = 
{0x22, 0x2d, 0x22, 0};
  static const JJChar tokenImage_arr_96[] = 
{0x22, 0x2f, 0x22, 0};
  static const JJChar tokenImage_arr_97[] = 
{0x22, 0x25, 0x22, 0};
  static const JJChar tokenImage_arr_98[] = 
{0x22, 0x7e, 0x22, 0};
  static const JJChar tokenImage_arr_99[] = 
{0x22, 0x21, 0x22, 0};
  static const JJChar tokenImage_arr_100[] = 
{0x22, 0x23, 0x22, 0};
  static const JJChar* const tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
tokenImage_arr_8, 
tokenImage_arr_9, 
tokenImage_arr_10, 
tokenImage_arr_11, 
tokenImage_arr_12, 
tokenImage_arr_13, 
tokenImage_arr_14, 
tokenImage_arr_15, 
tokenImage_arr_16, 
tokenImage_arr_17, 
tokenImage_arr_18, 
tokenImage_arr_19, 
tokenImage_arr_20, 
tokenImage_arr_21, 
tokenImage_arr_22, 
tokenImage_arr_23, 
tokenImage_arr_24, 
tokenImage_arr_25, 
tokenImage_arr_26, 
tokenImage_arr_27, 
tokenImage_arr_28, 
tokenImage_arr_29, 
tokenImage_arr_30, 
tokenImage_arr_31, 
tokenImage_arr_32, 
tokenImage_arr_33, 
tokenImage_arr_34, 
tokenImage_arr_35, 
tokenImage_arr_36, 
tokenImage_arr_37, 
tokenImage_arr_38, 
tokenImage_arr_39, 
tokenImage_arr_40, 
tokenImage_arr_41, 
tokenImage_arr_42, 
tokenImage_arr_43, 
tokenImage_arr_44, 
tokenImage_arr_45, 
tokenImage_arr_46, 
tokenImage_arr_47, 
tokenImage_arr_48, 
tokenImage_arr_49, 
tokenImage_arr_50, 
tokenImage_arr_51, 
tokenImage_arr_52, 
tokenImage_arr_53, 
tokenImage_arr_54, 
tokenImage_arr_55, 
tokenImage_arr_56, 
tokenImage_arr_57, 
tokenImage_arr_58, 
tokenImage_arr_59, 
tokenImage_arr_60, 
tokenImage_arr_61, 
tokenImage_arr_62, 
tokenImage_arr_63, 
tokenImage_arr_64, 
tokenImage_arr_65, 
tokenImage_arr_66, 
tokenImage_arr_67, 
tokenImage_arr_68, 
tokenImage_arr_69, 
tokenImage_arr_70, 
tokenImage_arr_71, 
tokenImage_arr_72, 
tokenImage_arr_73, 
tokenImage_arr_74, 
tokenImage_arr_75, 
tokenImage_arr_76, 
tokenImage_arr_77, 
tokenImage_arr_78, 
tokenImage_arr_79, 
tokenImage_arr_80, 
tokenImage_arr_81, 
tokenImage_arr_82, 
tokenImage_arr_83, 
tokenImage_arr_84, 
tokenImage_arr_85, 
tokenImage_arr_86, 
tokenImage_arr_87, 
tokenImage_arr_88, 
tokenImage_arr_89, 
tokenImage_arr_90, 
tokenImage_arr_91, 
tokenImage_arr_92, 
tokenImage_arr_93, 
tokenImage_arr_94, 
tokenImage_arr_95, 
tokenImage_arr_96, 
tokenImage_arr_97, 
tokenImage_arr_98, 
tokenImage_arr_99, 
tokenImage_arr_100, 
  };

#endif
