/* Generated By:JJTree: Do not edit this line. OrbTree.h Version 7.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ORBTREE_H
#define ORBTREE_H
#include "SimpleNode.h"
#endif
/* JavaCC - OriginalChecksum=f63fe2bccdbe6df18fc92c7bec6588af (do not edit this line) */
