/* Generated By:JJTree: Do not edit this line. SimpleNode.h Version 7.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef SIMPLENODE_H
#define SIMPLENODE_H
#include <vector>
#include "JavaCC.h"
#include "Token.h"
#include "Node.h"
#include "OrbTreeConstants.h"
#include <unordered_map>


class SimpleNode : public Node {
public:
    class VariantData
    {
    public:
        VariantData();
        VariantData(intptr_t val);
        VariantData(const JAVACC_CHAR_TYPE *val);
        VariantData(Token *val);
		VariantData(void *p);
		VariantData(SimpleNode *node);
        intptr_t toInt() const;
        const JAVACC_STRING_TYPE& toString() const;
        Token* toToken() const;
		void* toPointer() const;
		SimpleNode* toNode() const;

    private:
        int vt; //0=void* 1=string 2=intptr 3=token* 4=SimpleNode*
        union {
            void *pv;
            Token *token;
            intptr_t iv;
			SimpleNode *nv;
        };
        JAVACC_STRING_TYPE sv;
    };

protected: 
  std::vector<Node*> children;
  Node *             parent = nullptr;
  void *             value  = nullptr;
//int                numChildren;
  Token *            firstToken = nullptr;
  Token *            lastToken  = nullptr;
  Orb*    parser = nullptr;
  int                id;

  std::unordered_map<JAVACC_STRING_TYPE, VariantData> userDatas;

public: 
           SimpleNode(int id);
           SimpleNode(Orb *parser, int id);
  virtual ~SimpleNode();

//#if !NODE_FACTORY
//\#define jjtCreate(id) new SimpleNode(id)
//\#define jjtCreate(p, id) new SimpleNode(p, id)
//#fi

  virtual void           jjtOpen() const;
  virtual void           jjtClose() const;
  virtual void           jjtSetParent(Node *n);
  virtual Node *         jjtGetParent() const;
  virtual void           jjtAddChild(Node *n, size_t i);
  virtual Node *         jjtGetChild(size_t i) const;
  virtual size_t         jjtGetNumChildren() const;
//  virtual void           jjtSetValue(void * value);
//  virtual void *         jjtGetValue() const;

  virtual void           jjtSetUserData(const JAVACC_CHAR_TYPE *name, VariantData data);
  virtual const VariantData&   jjtGetUserData(const JAVACC_CHAR_TYPE *name);

  virtual Token *        jjtGetFirstToken() const;
  virtual Token *        jjtGetLastToken() const;
  virtual void           jjtSetFirstToken(Token *token);
  virtual void           jjtSetLastToken(Token *token);


  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(string), otherwise overriding toString() is probably all
     you need to do. */
  virtual JJString toString() const;
  virtual JJString toString(const JJString& prefix) const;

  /* Override this method if you want to customize how the node dumps
     out its children. */
  virtual void          dump(const JJString& prefix) const;
  virtual void          dumpToBuffer(const JJString& prefix, const JJString& separator, JJString *sb) const;
  virtual int           getId() const { return id;  }
};

#endif
/* JavaCC - OriginalChecksum=ffa1c6a078d2bbe4422da4c9ace95e67 (do not edit this line) */
